import { Poppins } from "next/font/google";
import "@/app/globals.css";
import Navbar from "@/components/Navbar";

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};



export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${poppins.className} bg-color-dark`}
				suppressHydrationWarning={true}>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
